name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: google-services.json and extra strings file
#      env:
#        GOOGLE_SERVICES_BASE64: ${{secrets.GOOGLE_SERVICES_BASE64}}
#        STRINGS_OTHER_BASE64: ${{secrets.STRINGS_OTHER}}
#      run: |
#         echo $GOOGLE_SERVICES_BASE64 | base64 --decode > ./app/google-services.json
#         echo $STRINGS_OTHER_BASE64 | base64 --decode > ./app/src/main/res/values/strings_other.xml
    - name: google-services.json and extra strings file (faked)
      run: |
          cp ./app/google-services.example ./app/google-services.json
          cp ./app/strings_other.xml.example ./app/src/main/res/values/strings_other.xml

    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: immich-tv-release-unsigned.apk
          path: ./app/build/outputs/apk/release/app-release-unsigned.apk